compositions/aws-provider/eks/definition.yaml, compositions/aws-provider/eks/eks-managed-node-group.yaml, compositions/aws-provider/eks/eks.yaml, examples/aws-provider/composite-resources/eks/eks-claim.yaml
*Issue #, if available:*
#8 
*Description of changes:*
- EKS Cluster with Managed Node groups
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> EKS managed node groups

README.md, bootstrap/terraform/main.tf, bootstrap/terraform/outputs.tf, bootstrap/terraform/values.yaml, bootstrap/terraform/variables.tf, bootstrap/terraform/versions.tf
- Updated the current source path for Terraform EKS Blueprints
- `Crossplane` Helm Chart update to `1.7.1`
- `aws_provider` update to `v0.27.0`
- `jet_aws_provider` to `v0.4.2`
- EKS Cluster upgrade to `1.22`
**Note**:
=> Terraform bootstrap example update

bootstrap/eksctl/README.md
=> docs: fix sed syntax in eksctl bootstrap guide

compositions/aws-provider/eks/definition.yaml, compositions/aws-provider/eks/eks-managed-node-group.yaml
This PR fixes the issue of the EKS composition writing an empty connection secret.
See issue #34 
- [X ] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [X ] Yes, I have linked to an issue or feature request (applicable to PRs that solves a bug or a feature request)
**Note**:
=> Correct EKS composition aggregated connection secret creation

bootstrap/terraform/crossplane-providers/kubernetes-provider.yaml, bootstrap/terraform/main.tf, bootstrap/terraform/outputs.tf, bootstrap/terraform/variables.tf, compositions/terrajet-aws-provider/s3/definition.yaml, compositions/terrajet-aws-provider/s3/s3-composition.yaml, examples/README.md, examples/kubernetes-provider/test-namespace.yaml, examples/terrajet-aws-provider/composite-resources/s3.yaml, examples/terrajet-aws-provider/managed-resources/kms.yaml, examples/terrajet-aws-provider/managed-resources/s3.yaml, examples/terrajet-aws-provider/managed-resources/vpc.yaml
:white_check_mark: S3 bucket composition with KMS Key with **Terrajet provider**
:white_check_mark: Managed resources examples for **Terrajet provider**
- S3 Bucket
- KMS Key
:white_check_mark: Kubernetes provider for Terraform bootstrap scripts. Fix for #15 
:white_check_mark: Kubernetes provider examples with docs
**Note**:
=> S3 and KMS composition examples

compositions/aws-provider/eks/definition.yaml
Signed-off-by: Diego Pinheiro <diego.milhomes@gmail.com>
Add version 1.23 in EKS XRD
Updated XRD  to reflect de available k8s versions in AWS.
**Note**:
=> Update EKS XRD - bump k8s version

doc/debugging.md
Adds a provider debugging guide to the debugging guide document. 
There is a lot of confusion around how providers are created and operated within Crossplane. This aims to help them debug their providers.
**Note**:
=> add provider debugging guide

compositions/terrajet-aws-provider/lambda/definitions.yaml, compositions/terrajet-aws-provider/lambda/zip.yaml, examples/terrajet-aws-provider/composite-resources/lambda-zip.yaml
Adds a general composition for lambda functions based on zip files. 
We currently have a composition for container based lambda functions but we don't have one for zip files. 
**Note**:
=> add lambda function with zip file

examples/aws-provider/composite-resources/s3/general-purpose.yaml, examples/aws-provider/composite-resources/s3/multi-tenant.yaml
Fixes the issue where example claim doesn't propagate secrets to its namespace.
=> fix bucket connection secret propagation

compositions/aws-provider/s3/general-purpose.yaml
fixes #52 
Buckets should be created in the region specified.
**Note**:
=> fix bucket region

.gitignore, README.md
- readme update to match with AWS guidelines
**Note**:
=> readme update to match with guidelines

examples/gatekeeper/managed-resource/README.md, examples/gatekeeper/managed-resource/samples/allowed.yaml, examples/gatekeeper/managed-resource/samples/constraint.yaml, examples/gatekeeper/managed-resource/samples/invalid_ownere_ref_disallowed.yaml, examples/gatekeeper/managed-resource/samples/missing_owner_ref_disallowed.yaml, examples/gatekeeper/managed-resource/suite.yaml, examples/gatekeeper/managed-resource/template.yaml
Adds an example policy for blocking managed resources. 
Current OPA example only blocks compositions based on claim name space, but there is no example for blocking creation of managed resources. 
**Note**:
=> Add example OPA policy for blocking managed resources

bootstrap/eksctl/crossplane/aws-provider.yaml
Update provider AWS version to match crossplane package specification: https://github.com/awslabs/crossplane-on-eks/blob/a543e27119774628c1cfbf1798ca40b648d23873/compositions/aws-provider/crossplane.yaml#L17
=> update aws provider version

README.md, bootstrap/terraform/README.md, bootstrap/terraform/main.tf, compositions/README.md, examples/README.md, tests/kuttl/test-suite.yaml, tests/kuttl/values.yaml
remove terrajet referrences
Clean up the repo
**Note**:
=> remove terrajet referrences

tests/kuttl/test-suite.yaml, tests/kuttl/values.yaml
Signed-off-by: Carlos Santana <csantana23@gmail.com>
update testing framework with latest version
**Note**:
=> update testing framework with latest version

compositions/aws-provider/example-application/example-application.yaml, compositions/aws-provider/iam-policy/definition.yaml, compositions/aws-provider/iam-policy/dynamodb-manage-table.yaml, compositions/aws-provider/iam-policy/dynamodb-read.yaml, compositions/aws-provider/iam-policy/dynamodb-write.yaml, doc/debugging.md, doc/nested-compositions.md, examples/aws-provider/composite-resources/iam/iam-dynamodb-read.yaml
Follow naming conventions for Composite and Claims XIAMPolicy
Found out that this is the only composite from the package not following the convention for naming Composite Resources (XR)
**Note**:
=> Follow naming conventions for Composite and Claims XIAMPolicy

examples/aws-provider/managed-resources/s3.yaml
Add example of s3 managed resource
I was looking for a simple example of s3
**Note**:
=> add s3 example with managed resource

doc/vault-integration.md
improve vault example docs
Minor fixes to command for vault setup, and update markdown to render code snippets with colors
**Note**:
=> improve vault example docs

bootstrap/terraform/README.md, bootstrap/terraform/main.tf, bootstrap/terraform/versions.tf
Adds the kubectl terraform provider version and config
Fixes #86 
**Note**:
=> add terraform kubectl provider config

bootstrap/eksctl/README.md
does a minor fix to the helm installation command
=> fix installation command

compositions/aws-provider/vpc-subnets/vpc-composition-networkid.yaml
ensures accurate selection from resources belonging to the same XR
it should be possible for several of these compositions to be deployed together
=> add controller ref for resource selection

README.md, doc/patching-101.md
Adds a documentation for basic patching mechanisms used in this repository. 
It's one of most frequently asked questions from our customers regarding this repository.
=> add patching doc

bootstrap/terraform/destroy.sh, bootstrap/terraform/main.tf, bootstrap/terraform/outputs.tf, bootstrap/terraform/variables.tf, bootstrap/terraform/versions.tf, examples/upbound-aws-provider/README.md, examples/upbound-aws-provider/managed-resources/s3/bucket.yaml
- upgrading k8s to 1.25
- moved EKS cluster creation to the official tf module
- updated tf providers to use exec plugin
- using SPOT instances and Karpenter for cost efficiency
- added in-cluster Prometheus
- upgraded Crossplane to latest
- upgraded both aws providers to latest
- enabled environment config and functions
- enabled metrics
Upgrades and preparation for terraform blueprints v5.
**Note**:
=> feat: Upgrading

bootstrap/terraform/main.tf
Update crossplane providers to latest version
Improving performance for aws upbound provider
**Note**:
=> update aws, kubernetes, helm providers

compositions/upbound-aws-provider/irsa/definition.yaml, compositions/upbound-aws-provider/irsa/irsa-exact.yaml, compositions/upbound-aws-provider/irsa/irsa-role-only.yaml, compositions/upbound-aws-provider/irsa/kustomization.yaml, examples/upbound-aws-provider/composite-resources/irsa.yaml
=> Add IRSA to Upbound Provider

compositions/aws-provider/s3/general-purpose.yaml, compositions/aws-provider/s3/multi-tenant.yaml
With the change to ACL to S3, current compositions for S3 do not work. This fixes it. 
More context is available here: https://github.com/crossplane-contrib/provider-aws/issues/1723
**Note**:
=> Fix bucket composition

compositions/aws-provider/eks/autoscaler.yaml, examples/aws-provider/composite-resources/eks/README.md, examples/aws-provider/composite-resources/eks/eks-cas-claim.yaml
Adds a composition for EKS with cluster autoscaler and aws-auth CM management.
=> add autoscaler composition

bootstrap/terraform/argocd-values.yaml, bootstrap/terraform/destroy.sh, bootstrap/terraform/main.tf, bootstrap/terraform/versions.tf
- Adds custom resource checks for Crossplane resources in ArgoCD
- Updates according to terraform blueprints v5
- Updates tf `helm_release` version to the latest due to prior slowness
- Updates crossplane versions to latest
This Kubecon EU talk: https://www.youtube.com/watch?v=VSZ_UoNNQXg
https://github.com/awslabs/crossplane-on-eks/issues/106
**Note**:
=> feat: ArgoCD configuration for Crossplane

bootstrap/terraform/argocd-values.yaml, bootstrap/terraform/main.tf
- Adds support for resource.customizations for both official and crontib aws-providers in the ArgoCD config.
- Makes the customizations conditional on provider being enabled
- ArgoCD config support for both providers
**Note**:
=> feat: ArgoCD config conditional on provider

bootstrap/terraform/main.tf
Updates the version of blueprints addon to avoid error
Fixes #139 
**Note**:
=> fix: blueprints addon version

compositions/upbound-aws-provider/s3-irsa/kustomization.yaml, examples/upbound-aws-provider/composite-resources/s3-irsa/argocd-s3-irsa-app.yaml, examples/upbound-aws-provider/composite-resources/s3-irsa/kustomization.yaml
- adding one missed kustomization file
- fixing argocd app
=> fix: s3-irsa-app

compositions/upbound-aws-provider/dynamo-irsa/dynamo-irsa.yaml, compositions/upbound-aws-provider/iam-policy/cloudwatch-metrics-write.yaml, compositions/upbound-aws-provider/iam-policy/definition.yaml, compositions/upbound-aws-provider/iam-policy/dynamodb-write.yaml, compositions/upbound-aws-provider/iam-policy/firehose-write.yaml, compositions/upbound-aws-provider/iam-policy/kms-read.yaml, compositions/upbound-aws-provider/iam-policy/lambda-invoke.yaml, compositions/upbound-aws-provider/iam-policy/s3-read.yaml, compositions/upbound-aws-provider/iam-policy/s3-write-firehose.yaml, compositions/upbound-aws-provider/iam-policy/s3-write.yaml, compositions/upbound-aws-provider/iam-policy/sqs-read.yaml, compositions/upbound-aws-provider/iam-policy/sqs-write.yaml, compositions/upbound-aws-provider/irsa/definition.yaml, compositions/upbound-aws-provider/irsa/irsa.yaml, compositions/upbound-aws-provider/kinesis-data-firehose-app/log-forwarder.yaml, compositions/upbound-aws-provider/s3-irsa/s3-irsa.yaml
Removes warning messages.
Now that Crossplane added schema validations, started getting warning messages while testing the compositions.
=> fix: warning messages

examples/gatekeeper/duplicate-s3/samples/allowed-bucket.yaml, examples/gatekeeper/duplicate-s3/samples/allowed-claim.yaml, examples/gatekeeper/duplicate-s3/samples/existing-buckets.yaml, examples/gatekeeper/duplicate-s3/samples/not-allowed-bucket.yaml, examples/gatekeeper/duplicate-s3/samples/not-allowed-claim.yaml, examples/gatekeeper/duplicate-s3/syncset.yaml
- Adding missing syncset
- Appending account id to bucket name to make it unique
- Adding provider details
Part of the IDP workshop.
- [] Yes, I have added a new example under [examples](https://github.com/aws-samples/crossplane-aws-blueprints/tree/main/examples) to support my PR
**Note**:
=> Duplicate S3 gatekeeper fixes

bootstrap/terraform/addon/main.tf
Updated Crossplane version to 1.15.0
It is latest Crossplane version with Composition Functions enabled by default
**Note**:
=> Updated Crossplane version to 1.15.0

compositions/upbound-aws-provider/serverless-microservice/functions.yaml, compositions/upbound-aws-provider/serverless-microservice/kustomization.yaml, compositions/upbound-aws-provider/serverless-microservice/rest-lambda-ddb.yaml, examples/upbound-aws-provider/composite-resources/serverless-examples/microservice/claim/.gitignore
Updated composition to use patch and transform composition function.
**Note**:
=> Updated microservice sample to use patch and transform function

bootstrap/terraform/providers/helm/runtime-config.yaml, bootstrap/terraform/providers/kubernetes/runtime-config.yaml
fixing typo in the runtimeconfig for helm and k8s
**Note**:
=> fixing typo in the runtimeconfig for helm and k8s
