compositions/aws-provider/rds/definition.yaml
compositions/aws-provider/rds/postgres-aurora.yaml
compositions/aws-provider/rds/rds-postgres.yaml
examples/aws-provider/composite-resources/rds/aurora-postgres.yaml
examples/aws-provider/composite-resources/rds/postgres.yaml

adds initial RDS compositions and examples
We need RDS compositions
**Note**:
RDS compositions use a work around to populate Security Groups correctly. This needs to be fixed in Crossplane core. 
https://github.com/crossplane/provider-aws/issues/1153

add initial RDS compositions

---

compositions/terrajet-aws-provider/lambda/container.yaml
compositions/terrajet-aws-provider/lambda/definitions.yaml
examples/terrajet-aws-provider/composite-resources/lambda.yaml

Adds an implementation of Lambda. The implementation creates a Lambda function from a container image with a basic role. More policies can be attached to this role using nested compositions. 
NOTE: The container composition consists of two resources from different providers because IAM role creation does not work in terrajet provider ATM: https://github.com/crossplane-contrib/provider-jet-aws/issues/176
Trying to complete AWS serverless resources
**Note**:

initial implementation of lambda

---

compositions/terrajet-aws-provider/vpc/definition.yaml
compositions/terrajet-aws-provider/vpc/vpc-composition.yaml
examples/terrajet-aws-provider/managed-resources/vpc.yaml

Signed-off-by: haarchri <chhaar30@googlemail.com>
followup for https://github.com/crossplane-contrib/provider-jet-aws/issues/162 
corrected the parameters for provider-jet-aws ec2/vpc resource 
- fixed example
- fixed definition
- fixed composition resource
**Note**:

fix(vpc-parameters):  fix for provider-jet-aws parameters ec2/vpc

---

compositions/aws-provider/eks/definition.yaml
compositions/aws-provider/eks/eks-managed-node-group-subnet-labels.yaml
compositions/aws-provider/eks/eks-managed-node-group.yaml
compositions/aws-provider/vpc-subnets/definition.yaml
compositions/aws-provider/vpc-subnets/vpc-composition-networkid.yaml
compositions/aws-provider/vpc-subnets/vpc-composition.yaml
examples/aws-provider/composite-resources/eks/eks-claim.yaml
examples/aws-provider/composite-resources/vpc-subnets-eks/vpc-subnets-eks-claims.yaml
examples/aws-provider/composite-resources/vpc-subnets/vpc-subnets-claim.yaml

This PR allows the composition in `compositions/aws-provider/eks` to use labels for automatically selecting subnets and replaces the current approach where subnet IDs manually needs to be inserted into the list of subnets. See also issue #32 
The EKS cluster composition in `compositions/aws-provider/eks` require manual specification of subnet Ids. In Kubernetes, labels are typically used to reference resources, i.e. labelling subnets and using the `resourcesVpcConfig.subnetIdSelector.matchLabels` feature of the `cluster.eks.crossplane.io` resource would be more convenient and less error prone. Prior art for this can be found in https://github.com/upbound/platform-ref-aws
The implementation in this PR implements the following
- Adds a new parameter `networkId` to the `xvpcsubnets` …

Use subnetIdSelector.matchLabels for subnet selection in EKS composition

---

README.md
examples/gatekeeper/provider-config-ns/kustomization.yaml
examples/gatekeeper/provider-config-ns/samples/allowed.yaml
examples/gatekeeper/provider-config-ns/samples/constraint.yaml
examples/gatekeeper/provider-config-ns/samples/missing_claim_disallowed.yaml
examples/gatekeeper/provider-config-ns/samples/namespace_mismatch_disallowed.yaml
examples/gatekeeper/provider-config-ns/samples/not_applicable_allowed.yaml
examples/gatekeeper/provider-config-ns/suite.yaml
examples/gatekeeper/provider-config-ns/template.yaml

Adds a Gatekeeper example for enforcing the provider config name selection based on claim's namespace.
**Note**:

add gatekeeper example to enforce provider config usage

---

README.md
examples/gatekeeper/provider-config-ns/README.md

Adding a readme to the gatekeeper example and fixes the link to vault integration example

add gatekeeper example readme

---

doc/debugging.md

Adds a diagram for the troubleshooting guide for easier understanding of object relationships.

add diagram for troubleshooting doc

---

compositions/aws-provider/eks/eks-managed-node-group-subnet-labels.yaml
compositions/aws-provider/eks/eks-managed-node-group.yaml
compositions/aws-provider/vpc-subnets/vpc-composition-networkid.yaml
compositions/aws-provider/vpc-subnets/vpc-composition.yaml
compositions/aws-provider/vpc/vpc-composition.yaml

Signed-off-by: Matthias Luebken <matthias.luebken@gmail.com>
Removes the yaml doc separator at the beginning of the yamls. While this is valid yaml definition they are considered optional: (https://yaml.org/spec/1.0/#id2561718) 
We are running into an [issue](https://github.com/crossplane/crossplane-runtime/issues/356) when [building a configuration package]( https://github.com/luebken/crossplane-aws-blueprints/pull/3#issuecomment-1256407271). The current xpkg spec doesn't consider it a valid spec.
**Note**:

Removes comment separators at the beginning

---

.gitignore
compositions/README.md
compositions/aws-provider/crossplane.yaml
compositions/terrajet-aws-provider/crossplane.yaml

Signed-off-by: Matthias Luebken <matthias.luebken@gmail.com>
Adds two configuration package definitions for the aws-provider and the terrajet-aws-provider and a readme addition that describes on how to build them. See https://crossplane.io/docs/v1.9/concepts/packages.html
Configuration packages are a convenient way to bundle and distribute crossplane definitions. Adding them here promotes this concept to the AWS blueprint community and might encourage further usage.
**Note**:

Configuration package definitions

---

bootstrap/eksctl/README.md

Update the Crossplane version to 1.10.1. 
This package requires Crossplane version above 1.9.0 and thus does not work.  https://github.com/awslabs/crossplane-on-eks/blob/90a2561468bdf9755fe2f4b9dcaa61295d40c647/compositions/aws-provider/crossplane.yaml#L14
**Note**:

update eksctl crossplane version

---

compositions/aws-provider/irsa/irsa-exact.yaml

Ensure IRSA creation fails when not used with a claim.

ensure irsa role creation fails when variables are not present

---

bootstrap/eksctl/crossplane/upbound-aws-provider-config.yaml
bootstrap/eksctl/crossplane/upbound-aws-provider.yaml

Adds configurations for the Upbound AWS provider. 
terrajet is being deprecated and we need to move to the Upbound providers.
**Note**:

add upbound aws provider 

---

compositions/aws-provider/iam-policy/definition.yaml
compositions/aws-provider/iam-policy/s3-read.yaml
compositions/aws-provider/iam-policy/s3-write.yaml

Adds IAM policy templates for read and write S3 objects
Access to S3 objects are common. We need to define one for reference by our customers.
**Note**:

Add s3 object read and write policies

---

compositions/aws-provider/example-application/definition.yaml
compositions/aws-provider/example-application/example-application.yaml
examples/aws-provider/composite-resources/example-application/example-application.yaml

Ensures example application secrets are created and add an example of using Kubernetes provider's dependency declaration. Note that It probably makes more sense to create a k8s secret in composition instead of relying on claim secret. I will likely do that in the future. 
@csantanapr mentioned how example application was not working in #72 
**Note**:

ensure example application secrets are created

---

compositions/aws-provider/iam-policy/dynamodb-manage-table.yaml
compositions/aws-provider/iam-policy/dynamodb-read.yaml
compositions/aws-provider/iam-policy/dynamodb-write.yaml

Removes `writeConnectionSecretsToNamespace` and let the default StoreConfig take care of it. This field is deprecated. https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.10.1#spec-writeConnectionSecretsToNamespace

remove write connection secrets field

---

compositions/aws-provider/irsa/irsa-exact.yaml
compositions/aws-provider/irsa/irsa-role-only.yaml

remove deprecated field and ensure SA is not created before the IAM role is created.
https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.10.1#spec-writeConnectionSecretsToNamespace

remove write connection secret

---

compositions/aws-provider/dynamodb/on-demand-composite-key.yaml
compositions/aws-provider/dynamodb/on-demand-partition-key.yaml
compositions/aws-provider/dynamodb/provisioned-composite-gsi.yaml
compositions/aws-provider/dynamodb/provisioned-composite-key.yaml
compositions/aws-provider/dynamodb/provisioned-composite-lsi.yaml
examples/aws-provider/composite-resources/dynamodb/dynamodb-on-demand-composite.yaml
examples/aws-provider/composite-resources/dynamodb/dynamodb-on-demand-partition.yaml
examples/aws-provider/composite-resources/dynamodb/dynamodb-provisioned-composite-gsi.yaml
examples/aws-provider/composite-resources/dynamodb/dynamodb-provisioned-composite-lsi.yaml
examples/aws-provider/composite-resources/dynamodb/dynamodb-provisioned-composite.yaml

imports dynamodb connection details directly from managed resource's status field instead of relying on undocumented secrets exported by the MR.
This also updates dynamodb compositions to use `publishConnectionDetailsTo` instead of `writeConnectionSecretToRef`. The latter is deprecated. 
It's not immediately clear where  connection details such as dynamod db table name and ARN are coming from in the previous example. This makes it clear where it is getting its information from.

ensure dynamodb connection secrets are populated

---

README.md

Removes the maintainer section from the README since we have the CODEOWNERS section
fewer places to update every time maintainers are updated/

clean up the readme and remove the maintainers section

---

bootstrap/eksctl/eksctl.yaml
bootstrap/terraform/main.tf

Set node size to `m5.large` for both eksctl and terraform
To allow user to run EMR on EKS
**Note**:

set default node size to m5.large

---

bootstrap/terraform/README.md
bootstrap/terraform/main.tf
bootstrap/terraform/values.yaml

Adds installation for `helm-provider` and `upbound-aws-provider`.
Resolves: https://github.com/awslabs/crossplane-on-eks/issues/9
Tested upbound aws-provider by successfully creating an S3 bucket:
```
cat <<EOF | kubectl create -f -
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
generateName: test-bucket-
spec:
forProvider:
region: us-east-1
providerConfigRef:
name: aws-provider-config
EOF
```
Tested helm provider by successfully creating a helm release:
```
cat <<EOF | kubectl create -f -
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
name: hello-example
spec:
forProvider:
chart:
name: hello
repository: https://cloudecho.github.io/charts
version: 0.1.2
namespace: hello-example
EOF
```

feat: adding upbound aws and helm providers

---

compositions/aws-provider/vpc-subnets/vpc-composition.yaml

Ensures controller refs are used in VPC compositions. This allows for multiple deployment of VPCs
**Note**:

Ensure controller refs are used in VPC compositions 

---

compositions/aws-provider/eks/definition.yaml
compositions/aws-provider/eks/eks-managed-node-group-subnet-labels.yaml
compositions/aws-provider/eks/eks-managed-node-group.yaml

1. Removes commented out fields
2. Add newer EKS versions to the enum
3. Add fields to support aws-auth config map management

update eks versions and remove duplicate printer fields

---

examples/upbound-aws-provider/managed-resources/s3/bucket.yaml

With this annotation the S3 bucket upbound-test-bucket was not able to be created due to permissions issues. IRSA was also checked and wired correctly.
Removing the annotation allows the bucket to be created with no issues.

Remove aws-provider-upbound-s3-bucket annotation when creating S3 bucket

---

bootstrap/terraform/README.md
bootstrap/terraform/main.tf
bootstrap/terraform/variables.tf
examples/upbound-aws-provider/composite-resources/databases/dynamo-irsa/README.md

- exposes some settings with variables instead of locals
- removing karpenter (it is not doing anything without configurations)
- adding gatekeeper
- updating addons to the latest release
- fixing a typo
https://github.com/awslabs/crossplane-on-eks/issues/147

feat: moving some tf locals to variables

---

bootstrap/terraform/kube-prometheus-stack-values.yaml
bootstrap/terraform/main.tf

- adds pod monitor for crossplane
- bumps grafana memory and cpu
- add simple dashboard for crossplane
First take on crossplane monitoring
**Note**:

feat: grafana updates and dashboard

---

examples/gatekeeper/region-restrict/README.md
examples/gatekeeper/region-restrict/samples/constraint.yaml
examples/gatekeeper/region-restrict/samples/sample-table-eu-west-2-pass.yaml
examples/gatekeeper/region-restrict/samples/sample-table-us-east-1-fail.yaml
examples/gatekeeper/region-restrict/suite.yaml
examples/gatekeeper/region-restrict/template.yaml
examples/gatekeeper/required-tags/README.md
examples/gatekeeper/required-tags/samples/constraint.yaml
examples/gatekeeper/required-tags/samples/dummy-table-missing-tag-fail.yaml
examples/gatekeeper/required-tags/samples/dummy-table-no-tags-fail.yaml
examples/gatekeeper/required-tags/samples/finance-table-pass.yaml
examples/gatekeeper/required-tags/suite.yaml
examples/gatekeeper/required-tags/template.yaml

Add two gatekeeper polices - one for restricting AWS regions that resources can be provisioned into, and the other is for preventing provisioning resources without the required tags.
Use the two new policies for creating labs on using Gatekeeper with Crossplane.
- [ X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
**Note**:

Additional gatekeeper policies

---

bootstrap/terraform/main.tf

This pull request updates the provider-upjet-aws version to v1.4.0 in Crossplane configuration. This version update addresses a critical issue where the ClusterAuth resource was incorrectly handling kubeconfig authorizations, leading to unauthorized errors when interacting with EKS clusters.
I found this issue with the ClusterAuth resource while using the provider-upjet-aws v1.3.0, where it resulted in unauthorized errors when trying to generate kubeconfig for EKS clusters. 
**Note**:
- https://github.com/crossplane-contrib/provider-upjet-aws/releases/tag/v1.4.0
- https://github.com/aws/aws-sdk-go-v2/issues/2567

fixing upjet aws provider v1.3.0 bug with ClusterAuth

---

ADOPTERS.md
README.md

This pull request updates the `ADOPTERS.md` file to include new organizations that are using Crossplane Blueprints for Amazon EKS. This addition helps showcase the growing community and usage of the project.
N/A
**Note**:
- Not all PRs require examples and docs.
- We prefer small, well-tested pull requests. Please ensure your pull requests are self-contained, and commits are squashed.
N/A

adding the adopters file

---

.github/workflows/publish-docs.yml
.gitignore
bootstrap/terraform/main.tf
bootstrap/terraform/values/prometheus.yaml
docs/.pages
docs/getting-started.md
docs/index.md
docs/patterns/vault-integration.md
mkdocs.yml

This PR fixes the existing issues with the GitHub Pages build process. it also introduces a new feature that allows users to switch between light and dark modes, enhancing UX of the doc.
here's my forked repo working: https://edgarsilva948.github.io/crossplane-on-eks/
we need to adjust the Repository -> Settings -> Pages to be:
- [] Yes, I have updated the [docs](https://github.com/aws-samples/crossplane-aws-blueprints/tree/main/doc) for this feature
**Note**:
N/A

Fix: github pages build

---

compositions/aws-provider/rds/postgres-aurora.yaml
compositions/aws-provider/rds/rds-postgres.yaml
examples/aws-provider/composite-resources/rds/aurora-postgres.yaml
examples/aws-provider/composite-resources/rds/postgres.yaml

This PR is to fix the issues with RDS Compositions and examples :
1. Engine version is fixed to update the depracated version. Depracated version no longer works and MR resource fails.
2. Fixing issue with password auto generation which is not working. Password auto generation is no longer supported and MOR resource fails.
3. Adding right namespace to passwords with password snippet for postgres example
Make RDS Compositions work.
**Note**:

Fixing Issues with RDS Compositions and Example.

---

.github/scripts/e2e-delete-lbs.py
.github/scripts/e2e-delete-sgs.py
.github/workflows/e2e-parallel-full.yml
bootstrap/terraform/versions.tf
docs/_partials/destroy.md

This PR adds the `e2e-parallel-full` GitHub Actions workflow by integrating automated cleanup of AWS resources (Security Groups and Load Balancers) and deploying infrastructure using Terraform.
#192 
**Note**:
- Not all the PRs require examples and docs.
- We prefer small, well-tested pull requests. Please ensure your pull requests are self-contained, and commits are squashed.
N/A

Adds e2e workflow with automated resource cleanup

---

bootstrap/eksctl/crossplane/argocd/argocd-values.yaml

Change the Lua code in the resource.customizations to address situations where Composite Resources stay in the Provisioning status forever, mainly for the ProviderConfig Kind.
It add tests for specific Kinds that does not have status or have just a status.users field. It also adds tests for the helm provider CRDs.
Based on the guide on https://docs.crossplane.io/latest/guides/crossplane-with-argo-cd/
To have a Composition deployed with ArgoCD and all resources with a green health status.
In the case of the Composition I was building, the ProviderConfig for kubernetes and for helm needed this fix to became green.
**Note**:

Setting ArgoCD Health Status for Crossplane/Upbound Specific Kinds

---

bootstrap/terraform/variables.tf

the default value for the helm provider should be true in the bootstrap
**Note**:

fix: changing the helm provider defaults to true

---

.github/scripts/e2e-delete-log-groups.py
.github/workflows/e2e-parallel-full.yml

This PR modifies the end-to-end test to ensure all dependencies are deleted before running the destroy command. This adjustment facilitates the application and destruction of clusters through GitHub CI.
**Note**:

fix: e2e test for terraform

---

bootstrap/terraform/main.tf

This PR updates the Terraform configuration by adjusting the depends_on parameters, resource wait times, and timeouts. These changes ensure that both terraform apply and terraform destroy commands execute smoothly from start to finish. Additionally, this PR addresses and resolves Issue #199.
#199 
**Note**:

fix: adjusting the terraform bootstrap to accelerate the creation/destroy

---

bootstrap/eksctl/crossplane/argocd/argocd-values.yaml
bootstrap/terraform/values/argocd.yaml

adjusts the terraform bootstrap to have the new script added to the eksctl here: #198 
#198 
**Note**:

fix: adding more resources in the lua script
